%YAML:1.0

stereo0:
  cam0:
    cam_overlaps: [1]
    camera_model: pinhole
    # k1 k2 p1 p2
    distortion_coeffs: [-0.27112431561517186, 0.05060829228589933, 0.0008875379580411214, -0.0023276495338537635]
    distortion_model: radtan
    #fx,fy,cx,cy
    intrinsics: [550.8035496757482, 493.22174462704123, 661.1263865968855, 303.1855486861886]
    resolution: [1280, 640]
    rostopic: /cam0/image_raw
  cam1:
    T_cn_cnm1:
      - [0.9999509436461581, 0.0004894496829122635, 0.00989296417593623, -0.07003079278398011]
      - [-0.0005603264721328329, 0.9999741893898487, 0.007162861745138554, 0.0011255174475208489]
      - [-0.00988920297208464, -0.007168053650973828, 0.9999254085537852, -0.0006298903345308758]
      - [0.0, 0.0, 0.0, 1.0]
    cam_overlaps: [0]
    camera_model: pinhole
    distortion_coeffs: [-0.2788646377570498, 0.05429183538657035, 0.0017190216772866181, 0.0004764791436115057]
    distortion_model: radtan
    intrinsics: [553.8719837106196, 494.1581133345531, 624.0414884734051, 273.4937625955584]
    resolution: [1280, 640]
    rostopic: /cam1/image_raw

#stereo1:
#  cam0:
#    cam_overlaps: [1]
#    camera_model: pinhole
#    distortion_coeffs: [-0.07807522319154642, 0.025474330348474093, 0.0025616979357020327, -0.007102076836766987]
#    distortion_model: radtan
#    intrinsics: [458.9941755661247, 455.8016918531219, 607.9941298534006, 276.00579278924045]
#    resolution: [1280, 640]
#    rostopic: /cam0/image_raw
#  cam1:
#    T_cn_cnm1:
#      - [0.9990119124689439, -0.0008490977342606747, -0.04443509624356887, -0.07135718699287925]
#      - [0.0007004969966300295, 0.9999941108957658, -0.003359684172510417, -0.00018345440984089662]
#      - [0.04443768726087427, 0.003325237859007696, 0.9990066239740757, -0.0009879237036078765]
#      - [0.0, 0.0, 0.0, 1.0]
#    cam_overlaps: [0]
#    camera_model: pinhole
#    distortion_coeffs: [-0.07730262746531577, 0.029819948716189437, 0.003852668193652757, 0.002590638935679709]
#    distortion_model: radtan
#    intrinsics: [457.677416784792, 455.6742596882402, 628.9087067256968, 277.53803548259305]
#    resolution: [1280, 640]
#    rostopic: /cam1/image_raw
