%YAML:1.0
stereo0:
  cam0:
    cam_overlaps: [1]
    camera_model: pinhole
    distortion_coeffs: [-0.2765923384169633, 0.09361708402477738, -0.0005801653285152212, -0.00026128310112907865, 0.06002369671681404, 0.10856712755511211, -0.11277132915081126, 0.15503123383549242]
    distortion_model: radtan
    intrinsics: [538.9007127537078, 479.55900394367995, 624.4350645509411, 312.6936571387903]
    resolution: [1280, 640]
    rostopic: /cam0/image_raw
  cam1:
    T_cn_cnm1:
      - [0.9999993238033439, -4.9271155109314976e-05, -0.0011618800317902192, -0.06971617593191541]
      - [4.54090556161024e-05, 0.999994475127288, -0.0033238009744298957, -0.000279060246862558]
      - [0.0011620373800642991, 0.003323745967011809, 0.9999938011717243, -0.00020692178472557596]
      - [0.0, 0.0, 0.0, 1.0]
    cam_overlaps: [0]
    camera_model: pinhole
    distortion_coeffs: [-0.32034378299307076, 0.10823824426278328, -0.00018835979487115943, -0.00012131183255179473, 0.07118152565299313, 0.06431487583549489, -0.11497054525179959, 0.17837504511909275]
    distortion_model: radtan
    intrinsics: [538.097982028488, 478.94676219130827, 646.9422297085631, 294.80927677910216]
    resolution: [1280, 640]
    rostopic: /cam1/image_raw

