%YAML:1.0
stereo0:
  cam0:
    cam_overlaps: [1]
    camera_model: pinhole
    distortion_coeffs: [-0.09180641476624987, 0.20015961625650597, -0.00025068620774585575, -0.00028742299009331984, 0.06027820285942616, 0.2781016880506778, 0.07415120991770795, 0.16915956157811535]
    distortion_model: radtan
    intrinsics: [527.4297034700951, 468.70073748100026, 642.110916834446, 306.69509024125335]
    resolution: [1280, 640]
    rostopic: /cam0/image_raw
  cam1:
    T_cn_cnm1:
      - [0.9999890956494688, 1.5372777881554957e-06, -0.004669965716603581, -0.06945571691820432]
      - [-2.121049423861032e-05, 0.99999112646458, -0.004212664503063748, -0.00015714051502033587]
      - [0.004669917801461815, 0.004212717618974264, 0.9999802222434153, -0.0002542894780810479]
      - [0.0, 0.0, 0.0, 1.0]
    cam_overlaps: [0]
    camera_model: pinhole
    distortion_coeffs: [-0.126016811108442, 0.057527914461609674, -0.0002652275251959659, 6.013869819819268e-05, 0.04396202270344915, 0.24284597858096296, -0.0825570730750639, 0.10930089498482275]
    distortion_model: radtan
    intrinsics: [526.2737884979572, 467.81519137703674, 650.2530828890187, 302.2145169789502]
    resolution: [1280, 640]
    rostopic: /cam1/image_raw
